#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 

#I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap          12


bspc config normal_border_color 	"#78615b"		
bspc config active_border_color		"#1d100c"
bspc config focused_border_color	"#dcb192"



bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled

# AUTOSTART

sh ~/apps/souris.sh &
feh --bg-fill /home/saad/Pictures/Wallpapers/21.jpg
picom --config /home/saad/.config/picom/picom.conf
$HOME/.config/dunst/wrapper.sh &
$HOME/.config/polybar/launchB.sh
