#! /bin/sh

#######################################
# autostart
#######################################

sxhkd &
feh --bg-scale /home/saad/Pictures/Wallpapers/30.jpg
$HOME/.config/dunst/wrapper.sh &
sh $HOME/.config/polybar.sh
picom --config ~/.config/picom/picom.conf
sh /home/saad/apps/souris.sh &
setxkbmap fr &



#######################################
# bsp window spacing
#######################################

bspc config top_padding 55
bspc config bottom_padding 25
bspc config left_padding 25
bspc config right_padding 25

bspc config top_monocle_padding -55
bspc config bottom_monocle_padding -25
bspc config left_monocle_padding -25
bspc config right_monocle_padding -25

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config border_width         3
bspc config window_gap          15


#######################################
# colors
#######################################

bspc config normal_border_color #78615B
bspc config focused_border_color #1D100C
bspc config presel_feedback_color #DCB192


#######################################
# misc
#######################################

bspc config focus_follows_pointer false
bspc config click_to_focus button1 

bspc monitor -d 1 2 3 4 5  

#######################################
# per-app config
#######################################

bspc rule -a Zathura state=tiled
